---
- name: Ubuntu Focal 20.04
  hosts: all
  vars:
    container_user: semaphore
  become: true
  become_user: root
  roles:
    - upgrade
    - system_tools
    - python
    - erlang
    - awscli
    - cloudwatch_agent
    - docker
    - users
    - agent
    - custom_roles
    - cleanup
